/// <reference path="../pb_data/types.d.ts" />
//
// 1700000015_narrow_write_rules.js, who may write where, for an existing install,
// with every membership check in the form PocketBase 0.22 evaluates fastest.
//
// GENERATED by scripts/gen-schema.mjs (the RULES block explains each rule). Do not
// edit by hand.
//
// Probed on PocketBase 0.22 with the old rules: a viewer could make themselves
// admin and remove the owner; anyone could move their own membership row into a
// workspace whose id they knew and read all of it; anyone signed in could create
// pages, tables, rows, comments, presence, Yjs updates and trash entries in a
// workspace they are not in. Every rule here is narrower than the one it replaces.
// The membership checks are also rewritten to a form proved to grant exactly the
// same access at about half the cost per check (the FASTER block explains it).
//
// Down does nothing on purpose: putting those rules back reopens the holes.

migrate(
  function (db) {
    var dao = new Dao(db);
    var rules = {
        "pages": {
            "listRule": "(@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id && (visibility != \"private\" || owner = @request.auth.id || editors:each ?= @request.auth.id || viewers:each ?= @request.auth.id)) || (publicToken != \"\" && publicToken = @request.query.token)",
            "viewRule": "(@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id && (visibility != \"private\" || owner = @request.auth.id || editors:each ?= @request.auth.id || viewers:each ?= @request.auth.id)) || (publicToken != \"\" && publicToken = @request.query.token)",
            "createRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id)",
            "updateRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id && (visibility != \"private\" || owner = @request.auth.id || editors:each ?= @request.auth.id) && (@request.data.workspace:isset = false || @request.data.workspace.workspace_members_via_workspace.user ?= @request.auth.id)",
            "deleteRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id && (visibility != \"private\" || owner = @request.auth.id || editors:each ?= @request.auth.id)"
        },
        "tables": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id)",
            "updateRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id) && (@request.data.workspace:isset = false || @request.data.workspace.workspace_members_via_workspace.user ?= @request.auth.id)",
            "deleteRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id"
        },
        "table_rows": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id)",
            "updateRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id) && (@request.data.workspace:isset = false || @request.data.workspace.workspace_members_via_workspace.user ?= @request.auth.id)",
            "deleteRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id"
        },
        "comments": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && author = @request.auth.id && (@collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id)",
            "updateRule": "author = @request.auth.id && @request.data.page:isset = false && @request.data.author:isset = false",
            "deleteRule": "author = @request.auth.id"
        },
        "presence": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && user = @request.auth.id && (@collection.workspace_members:pmem.workspace ?= page.workspace && @collection.workspace_members:pmem.user ?= @request.auth.id)",
            "updateRule": "user = @request.auth.id && (@request.data.user:isset = false || @request.data.user = @request.auth.id) && (@request.data.page:isset = false || @request.data.page.workspace.workspace_members_via_workspace.user ?= @request.auth.id)",
            "deleteRule": "user = @request.auth.id"
        },
        "workspace_members": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && @request.data.user = @request.auth.id && (@request.data.workspace.owner ?= @request.auth.id || (@collection.workspace_invites.workspace ?= @request.data.workspace && @collection.workspace_invites.email ?= @request.auth.email && @collection.workspace_invites.status ?= \"pending\" && @collection.workspace_invites.role ?= @request.data.role))",
            "updateRule": "@request.auth.id != \"\" && @request.data.workspace:isset = false && @request.data.user:isset = false && (@request.data.publicKey:isset = false || user = @request.auth.id) && ((workspace.owner = @request.auth.id || (@collection.workspace_members:adm.workspace ?= workspace && @collection.workspace_members:adm.user ?= @request.auth.id && @collection.workspace_members:adm.role ?= \"admin\")) || (user = @request.auth.id && @request.data.role:isset = false))",
            "deleteRule": "@request.auth.id != \"\" && (user = @request.auth.id || (workspace.owner = @request.auth.id || (@collection.workspace_members:adm.workspace ?= workspace && @collection.workspace_members:adm.user ?= @request.auth.id && @collection.workspace_members:adm.role ?= \"admin\")))"
        },
        "workspace_keys": {
            "listRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "updateRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id) && (user = @request.auth.id || (workspace.owner = @request.auth.id || (@collection.workspace_members:adm.workspace ?= workspace && @collection.workspace_members:adm.user ?= @request.auth.id && @collection.workspace_members:adm.role ?= \"admin\"))) && @request.data.workspace:isset = false",
            "deleteRule": "@request.auth.id != \"\" && (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id) && (user = @request.auth.id || (workspace.owner = @request.auth.id || (@collection.workspace_members:adm.workspace ?= workspace && @collection.workspace_members:adm.user ?= @request.auth.id && @collection.workspace_members:adm.role ?= \"admin\")))"
        },
        "yupdates": {
            "listRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "viewRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "createRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "updateRule": null,
            "deleteRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))"
        },
        "page_versions": {
            "listRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "viewRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "createRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "updateRule": null,
            "deleteRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))"
        },
        "uploads": {
            "listRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id",
            "viewRule": "",
            "createRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id))",
            "updateRule": null,
            "deleteRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id"
        },
        "file_trash": {
            "listRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id",
            "viewRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id",
            "createRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "updateRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id",
            "deleteRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id"
        },
        "reminders": {
            "listRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "viewRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "createRule": "@request.auth.id != \"\" && workspace != \"\" && @collection.workspace_members:mem.workspace ?= workspace && @collection.workspace_members:mem.user ?= @request.auth.id",
            "updateRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))",
            "deleteRule": "@request.auth.id != \"\" && (workspace = \"\" || (@collection.workspace_members.workspace ?= workspace && @collection.workspace_members.user ?= @request.auth.id))"
        }
    };
    Object.keys(rules).forEach(function (name) {
      var col;
      try {
        col = dao.findCollectionByNameOrId(name);
      } catch (e) {
        return; // not on this install
      }
      var r = rules[name];
      col.listRule = r.listRule;
      col.viewRule = r.viewRule;
      col.createRule = r.createRule;
      col.updateRule = r.updateRule;
      col.deleteRule = r.deleteRule;
      dao.saveCollection(col);
    });
  },
  function (db) {},
);
